/**
 * Binary STL writer
 */

#include "../include/stl_writer.h"
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* ============== STL Binary Format ==============
 * 
 * Header:     80 bytes (usually ASCII description, we leave blank)
 * Count:      4 bytes (uint32_t, number of triangles)
 * Triangles:  50 bytes each
 *   - Normal: 12 bytes (3x float32)
 *   - V1:     12 bytes (3x float32)
 *   - V2:     12 bytes (3x float32)
 *   - V3:     12 bytes (3x float32)
 *   - Attr:   2 bytes (uint16_t, attribute count, usually 0)
 */

#define STL_HEADER_SIZE 80
#define STL_TRIANGLE_SIZE 50

/* ============== Writer Implementation ============== */

stl_writer_t* stl_writer_open(const char* path) {
    FILE* f = fopen(path, "wb");
    if (!f) return NULL;
    
    stl_writer_t* w = malloc(sizeof(stl_writer_t));
    if (!w) {
        fclose(f);
        return NULL;
    }
    
    w->file = f;
    w->triangle_count = 0;
    
    // Write empty header
    char header[STL_HEADER_SIZE] = {0};
    snprintf(header, STL_HEADER_SIZE, "Binary STL generated by libterrain");
    fwrite(header, 1, STL_HEADER_SIZE, f);
    
    // Remember position for triangle count
    w->header_pos = ftell(f);
    
    // Write placeholder count (will update on close)
    uint32_t zero = 0;
    fwrite(&zero, sizeof(uint32_t), 1, f);
    
    return w;
}

int stl_writer_close(stl_writer_t* writer) {
    if (!writer) return -1;
    
    // Seek back and write triangle count
    fseek(writer->file, writer->header_pos, SEEK_SET);
    fwrite(&writer->triangle_count, sizeof(uint32_t), 1, writer->file);
    
    fclose(writer->file);
    free(writer);
    
    return 0;
}

stl_vec3_t stl_compute_normal(stl_vec3_t v1, stl_vec3_t v2, stl_vec3_t v3) {
    // Edge vectors
    float ax = v2.x - v1.x;
    float ay = v2.y - v1.y;
    float az = v2.z - v1.z;
    
    float bx = v3.x - v1.x;
    float by = v3.y - v1.y;
    float bz = v3.z - v1.z;
    
    // Cross product
    stl_vec3_t n;
    n.x = ay * bz - az * by;
    n.y = az * bx - ax * bz;
    n.z = ax * by - ay * bx;
    
    // Normalize
    float len = sqrtf(n.x*n.x + n.y*n.y + n.z*n.z);
    if (len > 0.0001f) {
        n.x /= len;
        n.y /= len;
        n.z /= len;
    }
    
    return n;
}

int stl_add_triangle(stl_writer_t* writer, const stl_triangle_t* tri) {
    if (!writer || !writer->file) return -1;
    
    // Write normal
    fwrite(&tri->normal.x, sizeof(float), 1, writer->file);
    fwrite(&tri->normal.y, sizeof(float), 1, writer->file);
    fwrite(&tri->normal.z, sizeof(float), 1, writer->file);
    
    // Write vertices
    fwrite(&tri->v1.x, sizeof(float), 1, writer->file);
    fwrite(&tri->v1.y, sizeof(float), 1, writer->file);
    fwrite(&tri->v1.z, sizeof(float), 1, writer->file);
    
    fwrite(&tri->v2.x, sizeof(float), 1, writer->file);
    fwrite(&tri->v2.y, sizeof(float), 1, writer->file);
    fwrite(&tri->v2.z, sizeof(float), 1, writer->file);
    
    fwrite(&tri->v3.x, sizeof(float), 1, writer->file);
    fwrite(&tri->v3.y, sizeof(float), 1, writer->file);
    fwrite(&tri->v3.z, sizeof(float), 1, writer->file);
    
    // Write attribute byte count (0)
    uint16_t attr = tri->attr;
    fwrite(&attr, sizeof(uint16_t), 1, writer->file);
    
    writer->triangle_count++;
    return 0;
}

int stl_add_triangle_verts(
    stl_writer_t* writer,
    stl_vec3_t v1,
    stl_vec3_t v2,
    stl_vec3_t v3
) {
    stl_triangle_t tri;
    tri.normal = stl_compute_normal(v1, v2, v3);
    tri.v1 = v1;
    tri.v2 = v2;
    tri.v3 = v3;
    tri.attr = 0;
    
    return stl_add_triangle(writer, &tri);
}

uint32_t stl_get_triangle_count(const stl_writer_t* writer) {
    return writer ? writer->triangle_count : 0;
}

int stl_add_quad(
    stl_writer_t* writer,
    stl_vec3_t a, stl_vec3_t b,
    stl_vec3_t c, stl_vec3_t d
) {
    // Split quad into two triangles
    // a--b    Triangle 1: a, b, c
    // |  |    Triangle 2: a, c, d
    // d--c
    
    int r1 = stl_add_triangle_verts(writer, a, b, c);
    int r2 = stl_add_triangle_verts(writer, a, c, d);
    
    return (r1 == 0 && r2 == 0) ? 0 : -1;
}

int stl_add_wall_segment(
    stl_writer_t* writer,
    float x, float y,
    float h_top, float h_bottom,
    float x_prev, float h_top_prev, float h_bottom_prev,
    int flip_normal
) {
    stl_vec3_t a = { x, y, h_top };
    stl_vec3_t b = { x_prev, y, h_top_prev };
    stl_vec3_t c = { x_prev, y, h_bottom_prev };
    stl_vec3_t d = { x, y, h_bottom };
    
    if (flip_normal) {
        return stl_add_quad(writer, b, a, d, c);
    } else {
        return stl_add_quad(writer, a, b, c, d);
    }
}